
[ingame]
	#Range: 1 ~ 10
	long_press_count = 2
	show_health_indicator = true
	show_target_indicator = true
	filter_animation = true
	#Range: 0.0 ~ 1.0
	laser_pointer_color = 0.328125
	enable_laser_pointer = true
	camera_auto_switch = true
	auto_preparation = false
	off_gore = false
	battle_autoswitch_items = []
	mining_autoswitch_items = ["cgm:assault_rifle", "cgm:bazooka", "cgm:grenade", "cgm:grenade_launcher", "cgm:heavy_rifle", "cgm:light_grip", "cgm:light_stock", "cgm:long_scope", "cgm:machine_pistol", "cgm:medium_scope", "cgm:mini_gun", "cgm:missile", "cgm:pistol", "cgm:rifle", "cgm:shell", "cgm:stun_grenade"]

