
#Puddles Settings
[Puddles]
	#How fast puddles generate - (0-5 is reasonable) Default: 5
	#Range: 0 ~ 1200
	puddleRate = 5
	#How fast puddles evaporate. Default: 40
	#Range: 0 ~ 100
	puddleEvaporationRate = 50
	#Biome blacklist
	biomeBlacklist = []

