
[General]
	#Limit for physics update queue
	#Range: 100 ~ 500000
	maxQueueLen = 10000
	#Limit for support check task chain
	#Range: -1 ~ 1024
	downCheckLimit = 30
	#Limit for falling entities
	#Range: 100 ~ 10000
	maxFallingBlocks = 1000
	#UwU
	debug = false
	#Should smashed blocks drop
	dropDestroyedBlocks = true
	#WIP
	explosionFire = true
	#Range: 0.0 ~ 100.0
	explosionMultiplier = 2.0
	#Should player trigger blocks under feet
	triggerOnStep = true
	#Range: 0.0 ~ 999999.0
	damageMultiplier = 1.0
	#Dimensions without physics
	dimensionBlacklist = ["minecraft:the_end"]

