name: Build Minecraft Server

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: Install Forge Server
        run: |
          java -jar installer.jar --installServer server
      - name: Copy Mods
        run: |
          mkdir -p config
          mkdir -p mods
          cp -r config ./server/config
          cp -r mods ./server/mods
      - name: Rename server executable to a standard format
        run: |
          mv ./server/forge*.jar ./server/server.jar

      - run: zip -r server.zip .
        working-directory: server

      - uses: actions/upload-artifact@v3
        with:
          path: server/server.zip
